"""remove unused transaction fields

Revision ID: bec5d4993610
Revises: c5012df61575
Create Date: 2025-12-21 18:31:50.212490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bec5d4993610'
down_revision: Union[str, None] = 'c5012df61575'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'card_type')
    op.drop_column('transactions', 'payer_email')
    op.drop_column('transactions', 'payer_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('payer_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('payer_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('card_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
