"""add_multiuse_fields

Revision ID: c5012df61575
Revises: acf2a2836d1e
Create Date: 2025-12-21 17:12:17.698749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5012df61575'
down_revision: Union[str, None] = 'acf2a2836d1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Agregar columnas con valores por defecto para datos existentes
    op.add_column('payment_links', sa.Column('single_use', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('payment_links', sa.Column('times_paid', sa.Integer(), nullable=False, server_default='0'))

    # Actualizar times_paid=1 para links ya pagados
    op.execute("UPDATE payment_links SET times_paid = 1 WHERE status = 'PAID'")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_links', 'times_paid')
    op.drop_column('payment_links', 'single_use')
    # ### end Alembic commands ###
